### ISSUE TITLE
部分Tex文件名大小写不一致

### ISSUE THREAD

**Issue by i-Pear** [NiuTrans/MTBook#10]
Chapter6\Chapter6.tex
Chapter7\Chapter7.tex
ChapterAppend\ChapterAppend.tex
与mt-book-xelatex.tex中139~141行中文件名大小写不一致，此问题导致在对文件名大小写敏感的操作系统（如大多数Linux）上编译会丢失章节

另外，Chapter1、2、3中所有对Figures的引用均为小写，同样会导致找不到src目录下文件；Chapter6、7也存在少量文件名大小写不符情况

**Comment by xiaotong** [comment]
感谢建议。这个问题我们确实没有注意到，可能是因为我们都是在windows和mac上测试的缘故。我们会更新代码，确保能在linux等系统上编译。

**Comment by xiaotong** [comment]
新版已解决
