### ISSUE TITLE
语料很少怎么办？

### ISSUE THREAD

**Issue by ma-my** [NiuTrans/MTBook#11]
在神经机器翻译中，如果数据很少，或者甚至没有平行语句的情况，还能训练翻译模型吗

**Comment by xiaotong** [comment]
数据量很少确实是一个挑战。实际上，神经机器翻译翻译中也有一些无指导的方法，可以在没有平行数据或者只有极少数平行数据的情况下训练系统，不过无指导机器翻译对于不同语言的表现差异较大，翻译效果还要看具体任务。从我个人的经验上看，无指导机器翻译的效果离实用还有一段距离。可以参看一下第七章最后一部分的内容，有一些介绍https://opensource.niutrans.com/mtbook/section7-6.html

还有，https://opensource.niutrans.com/mtbook/section7-6.html 也给出了一些常用的数据集，很多都可以免费获取，用于科研任务是没问题的。

**Comment by lidongxing** [comment]
unsupervised nmt：back-translation，有点类似autoencoder
