### ISSUE TITLE
CMD端编译出错

### ISSUE THREAD

**Issue by JiangMingchen** [NiuTrans/MTBook#12]
在CMD端执行xelatex mt-book-xelatex后报错如下：
Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\lenovo\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log

dvipdfmx:fatal: File ended prematurely

No output PDF file written.

之前有两处出现”! Undefined control sequence.“

**Comment by xiaotong** [comment]
谢谢反馈。我们先尝试复现一下问题。

**Comment by mengxia-mx** [comment]
你好，我们团队的成员没有出现这种状况，但是我下载安装了最新的miktex后，也出现了这种情况。我打开了C:\Users\lenovo\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log，观察到里面非常重要的信息：FATAL xelatex.core - No space on device。问题主要是“No space left on device”，解决方法就是设置命令行的字符集 ，执行下面命令就好了：
chcp 65001
xelatex --shell-escape mt-book-xelatex.tex
网络上的其他朋友也遇到了相同的问题，在这里有位朋友给出了解决办法：https://github.com/dustincys/hithesis/issues/26。
我也是参照他的方法做的，成功将问题解决了。

**Comment by mengxia-mx** [comment]
关于”! Undefined control sequence.“的问题，直接回车就可以。

**Comment by JiangMingchen** [comment]
谢谢你们的帮助，问题已经成功解决！

**Comment by mengxia-mx** [comment]
刚才发现”! Undefined control sequence.“的问题有其他人提出来，有人提出了解决方案：你可以将xeCJK.sty文件中报错的代码删除后即可正常编译(推测于这个文件的版本有关)。 @JiangMingchen 
![83342093-92f01800-a2da-11ea-9d00-e6e55198b2e2](https://user-images.githubusercontent.com/32760451/83342182-b6d54d00-a31e-11ea-98b3-43fbcdd85eab.jpg)
