### ISSUE TITLE
transformer mask 时表述不太对

### ISSUE THREAD

**Issue by 520jefferson** [NiuTrans/MTBook#14]
![image](https://user-images.githubusercontent.com/5691554/82733092-1a221680-9d44-11ea-87f7-774961b59c9e.png)
直接把需要mask的地方设置为负无穷，不是相加吧

**Comment by libeineu** [comment]
您好，十分感谢对我们书中细节的关注，书中含义是指将Mask矩阵中需要被mask的位置设置为负无穷，之后与对应向量进行累加，即可达到屏蔽的效果（Softmax负无穷为0）。和您提出的将对应位置设置成负无穷是相当的，仅仅是实现方式的区别，但核心宗旨都是一样的。同时目前比较广泛使用的开源系统也大多采用上述方式进行实现（可以参考Tensor2Tensor）。

**Comment by lyy1994** [comment]
你好，这是具体实现方法的问题，本质我们都是希望想要Mask的位置的值变成负无穷，直接把需要Mask的位置设置成负无穷是一种方案，而累加Mask矩阵的方式利用了负无穷和任意实数相加结果仍为负无穷的性质，最后两者产生的结果是等价的。

**Comment by 520jefferson** [comment]
> 你好，这是具体实现方法的问题，本质我们都是希望想要Mask的位置的值变成负无穷，直接把需要Mask的位置设置成负无穷是一种方案，而累加Mask矩阵的方式利用了负无穷和任意实数相加结果仍为负无穷的性质，最后两者产生的结果是等价的。

非常感谢耐心解答！谢谢你们的工作
