### ISSUE TITLE
内存不足导致报错的问题

### ISSUE THREAD

**Issue by takagi97** [NiuTrans/MTBook#15]
为什么我按照内存不足的解决方法执行了之后，还是不能够编译整个文档呢？还是会报错内存溢出

**Comment by isZengxin** [comment]
你好，应该是你修改的配置文件没有起作用。你可以试试：进入cmd ；切换到mt-book-xelatex.tex所在文件夹 （如：cd C:\Tex\Book）；然后分别运行
xelatex --extra-mem-top=1000000 mt-book-xelatex
biber mt-book-xelatex
makeindex mt-book-xelatex
xelatex --extra-mem-top=1000000 mt-book-xelatex

**Comment by takagi97** [comment]
thanku！
