### ISSUE TITLE
初次使用miktex，在编译时遇到Undefined control sequence.问题

### ISSUE THREAD

**Issue by unk-alt** [NiuTrans/MTBook#17]
!Undefined control sequence.
<argument> \__xeCJK_patch_microtype_get_slot: 
                                              
l.4826   }
请教一下这样的问题该如何处理？

**Comment by bigheadcrz** [comment]
这个问题在已经关闭的问题中提到过，你可以将xeCJK.tsy文件中报错的代码删除后即可正常编译(推测于这个文件的版本有关)。
![mmexport1590886809945](https://user-images.githubusercontent.com/38352379/83342063-31c84480-a2da-11ea-8ab7-4b08163d7eb9.jpg)

**Comment by bigheadcrz** [comment]
这个问题在已经关闭的问题中提到过，你可以将xeCJK.sty文件中报错的代码删除后即可正常编译(推测于这个文件的版本有关)。
![mmexport1590886809945](https://user-images.githubusercontent.com/38352379/83342093-92f01800-a2da-11ea-9d00-e6e55198b2e2.jpg)

**Comment by xiaotong** [comment]
直接在命令行里敲回车就行

**Comment by bigheadcrz** [comment]
> 直接在命令行里敲回车就行

老师，这个方法的确可以编译，但是会使参考文献的显示出现问题，上面注释掉源码的方式，不会造成其他问题，相对来说更好一些

**Comment by xiaotong** [comment]
学习了，赞！

**Comment by unk-alt** [comment]
感谢！问题解决了
