### ISSUE TITLE
在cmd编译过程中输入第二个命令后出现错误

### ISSUE THREAD

**Issue by 1024-program** [NiuTrans/MTBook#18]
![QQ图片20200531095153](https://user-images.githubusercontent.com/52871626/83342663-927c6f00-a324-11ea-9a24-338f02de5e70.png)

**Comment by mengxia-mx** [comment]
你好，一般出现这个问题是因为第一步xelatex mt-book-xelatex就出现了问题。如果第一步成功生成了pdf,应该是内存不足导致的pdf信息生成的不完全，只要先扩充内存，然后删掉中间文件，重新运行就可以解决了。
扩充内存的方法：
Windows下使用MiKTeX或CTEX
1. 运行cmd打开命令行窗口，输入：initexmf --edit-config-file=xelatex
2. 在弹出的文件中输入以下内容：main_memory=5000000 extra_mem_bot=5000000 font_mem_size=5000000 pool_size=5000000 buf_size=5000000
3. 在cmd窗口输入： initexmf --dump=xelatex 更新latex格式文件

TeXLive & MacTeX（Linux，OS X等）
1. 打开texmf.cnf文件，更改其内容为：main_memory=5000000 extra_mem_bot=5000000 font_mem_size=5000000 pool_size=5000000 buf_size=5000000
2. 调用texhash更新latex格式文件
