### ISSUE TITLE
引入文件拼写错误

### ISSUE THREAD

**Issue by zhangchanggong** [NiuTrans/MTBook#19]
mt-book-xelatex.tex 文件
line 136，139-141
include 的文件名与实际不符
tex studio 中报错，建议修改实际文件名

**Comment by bigheadcrz** [comment]
谢谢反馈，我们也发现了这个问题，会尽快解决

**Comment by zhangchanggong** [comment]
用不用我来改一遍！我这边的环境就是linux的！

**Comment by bigheadcrz** [comment]
> 用不用我来改一遍！我这边的环境就是linux的！

谢谢，我们已经改了一遍，你试试在Linux可以正常运行吗

**Comment by zhangchanggong** [comment]
linux 下 基于 texlive 2020 编译没问题。













在 2020-06-07 14:33:24，"Tong Xiao" <notifications@github.com> 写道：

Closed #19.
