### ISSUE TITLE
4.1章 page135 

### ISSUE THREAD

**Issue by lidongxing** [NiuTrans/MTBook#22]
p('红 茶'='red tea')=0.8*0.8=0.64
p('红茶'='black tea')=0.6

此处文字描述有误

**Comment by xiaotong** [comment]
感谢指出问题。我们会在新版中进行修正。

**Comment by shanweiqiao** [comment]
> p('红 茶'='red tea')=0.8*0.8=0.64
> p('红茶'='black tea')=0.6
> 
> 此处文字描述有误

同学你好，感谢你的回复。

这块我是这样理解的，我认为应该比较整句的翻译概率。即，比较P(我 -> I)*P(喜欢 -> like)*P(红 -> red)*P(茶 -> tea)，P(我 -> I)*P(喜欢 -> like)*P(红茶 -> black tea)，P(我喜欢 -> I like)*P(红茶 -> black tea)等等全部短语的全部组合结果的概率值大小。在已给概率中P(我喜欢)*P(红茶)=0.18的概率最高，所以是选择这种组合作为正确结果。

这是否回答了你的疑问呢？

**Comment by lidongxing** [comment]
@shanweiqiao 可明显P(我喜欢)*P(红)*P(茶)='I like' 'red' 'tea' = 0.3 *0.8*0.8=0.192 > P(我喜欢)*P(红茶)=0.3 * 0.6 =0.18， P(我喜欢)*P(红茶)=0.18不是概率最高

**Comment by shanweiqiao** [comment]
ok，明白了，这块概率有问题，而且文字也有问题，感谢指正




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lidongxing"<notifications@github.com&gt;; 
发送时间: 2020年6月7日(星期天) 中午12:09
收件人: "NiuTrans/MTBook"<MTBook@noreply.github.com&gt;; 
抄送: "等到风景都看透"<1024476687@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NiuTrans/MTBook] 4.1章 page135  (#22)





 
@shanweiqiao 可明显P(我喜欢)*P(红)*P(茶)='I like' 'red' 'tea' = 0.3 0.80.8=0.192 &gt; P(我喜欢)*P(红茶)=0.3 * 0.6 =0.18， P(我喜欢)*P(红茶)=0.18不是概率最高

**Comment by shanweiqiao** [comment]
> @shanweiqiao 可明显P(我喜欢)*P(红)*P(茶)='I like' 'red' 'tea' = 0.3 _0.8_0.8=0.192 > P(我喜欢)*P(红茶)=0.3 * 0.6 =0.18， P(我喜欢)*P(红茶)=0.18不是概率最高

好的，明白了，感谢指正
