### ISSUE TITLE
Page 90-91 include Pig 3.4

### ISSUE THREAD

**Issue by lidongxing** [NiuTrans/MTBook#23]
机器翻译---词翻译模型中的第二个问题，1. 用比较整个句子的统计概率大小解决问题，明显每个词的翻译的最大概率词构成的句子的概率值最大，2.在词翻译模型中，机器是怎么学到的statisfied 后是with 而不是statisfied to.
3. 图3.4 中，在解决了第一个问题后，用统计枚举算，共54中可能。用最大概率计算，应该不是第一条路径最佳。
4.这个图的概率值有误。

谢谢辛苦的工作。

**Comment by xiaotong** [comment]
谢谢你问题。

**Comment by xiaotong** [comment]
1. 用比较整个句子的统计概率大小解决问题，明显每个词的翻译的最大概率词构成的句子的概率值最大
>> 是的，如果是按词来建模，如果单词之间是独立的，翻译概率最大的就是每个单词候选翻译概率最大的译文。但是，在机器翻译中会考虑目标语译文的流畅度，比如，不同单词之间的搭配。通常会引入语言模型，这是即使单词翻译概率高，但是语言模型得分低，仍然无法确保译文得分最高。这部分内容在第三章也有论述。

2.在词翻译模型中，机器是怎么学到的statisfied 后是with 而不是statisfied to.
实际上在IBM模型3-5里引入了产出率的概念，其目的是捕捉一个单词生成多个单词的情况。此外，基于短语和基于句法的模型也可以很好的处理局部依赖。

3. 图3.4 中，在解决了第一个问题后，用统计枚举算，共54中可能。用最大概率计算，应该不是第一条路径最佳。
>> 是的，如果仅考虑单词翻译概率是这样的。我们引入语言模型后，最终的模型得分会有不同。我们会再确认例子的合理性。

4.这个图的概率值有误。
>> 我们会再检查一下。

**Comment by lidongxing** [comment]
好的，谢谢您的回答
