### ISSUE TITLE
4.2 P149

### ISSUE THREAD

**Issue by lidongxing** [NiuTrans/MTBook#24]
“在桌子上的”应为‘on the table’

**Comment by shanweiqiao** [comment]
> “在桌子上的”应为‘on the table’

您好，感谢您的指正，如果方便的话能否提供一下更具体的位置信息，因为不知道您现在用何种方式在阅读本书，不同版本的pdf页数稍有不同

**Comment by shanweiqiao** [comment]
> “在桌子上的”应为‘on the table’

您的意思是在例20的描述中，用“the apple”和“on the table”或者“苹果”和“在桌子上的”描述调序距离吗

**Comment by lidongxing** [comment]
@shanweiqiao 是的

**Comment by shanweiqiao** [comment]
> @shanweiqiao 是的

收到，感谢您
