### ISSUE TITLE
! TeX capacity exceeded, sorry [main memory size=3000000]

### ISSUE THREAD

**Issue by Ingsuifon** [NiuTrans/MTBook#3]
I use the solution that you have given，but the result has no change

**Comment by xiaotong** [comment]
谢谢对我们的内容感兴趣。我猜测可能是你电脑内存的限制，由于tex图片过多，内存小的时候仍然抱错。后面我们也会那tex图片编译成pdf直接引用，可以缓解这个问题。

**Comment by Ingsuifon** [comment]
Excuse me, but do you really have tried the solution? The first step of the way is to modify the ini file of **xelatex**: 
`initexmf --edit-config-file=xelatex`
 but look at the third step, it finally acts on the **pdflatex** :
`initexmf --dump=pdflatex`
Please be careful! It has waste my time, so I don't want it continue to waste other's time. The right way is to modify the ini files both of them.

**Comment by bigheadcrz** [comment]
> 
> 
> Excuse me, but do you really have tried the solution? The first step of the way is to modify the ini file of **xelatex**:
> `initexmf --edit-config-file=xelatex`
> but look at the third step, it finally acts on the **pdflatex** :
> `initexmf --dump=pdflatex`
> Please be careful! It has waste my time, so I don't want it continue to waste other's time. The right way is to modify the ini files both of them.

**Comment by bigheadcrz** [comment]
的确是我们命令书写出现了错误，前后命令不一致，现在问题已经解决了，谢谢你的反馈
