### ISSUE TITLE
请问神经机器翻译中，对于小语种的训练应该怎么做呢？

### ISSUE THREAD

**Issue by WIFIergege** [NiuTrans/MTBook#32]
在神经机器翻译中，我已经收集到不少数据，但是出现的问题是，中文到英文准确度可以保证，当设置平行语句时总会出问题，并且在训练过程中，日语和韩语这两种语言与中文的转换并不准确，韩语与日语中有很多语法与中文语法不同，所以想请教一下大佬们，有没有好的建议，还有就是在训练中，如果一句话中加入表情，那么识别语种会有问题，并且表情符号也会被吞掉，以上这几个问题请问有没有好的解决办法呢？

**Comment by xiaozhang521** [comment]
你好，会不会是在数据清洗的时候没有做好，如果是句子之间没有对齐，简单的一些方式如词对齐，长度比等等策略可以将没有对齐的句子去掉。然后日语和韩语与中文的转换不准确这个问题，不太清楚训练预料的数量是多少，毕竟日语还有有一些汉字在的，相较于英语，日语还算比较接近的语言，感觉还是训练语料太少或者训练语料质量不够噪声太多，或者模型的参数没有调整好没有收敛等等问题。然后加入表情实识别语种会有问题，可以写一个脚本利用unicode先把这些符号过滤掉吧，看看哪些符号不属于中文，韩文，日文字符的，再用语言识别工具。或者多测试一些语言识别工具，看是不是都会有这个问题。对于题目中小语种的训练应该怎么做，实际上是一个很广泛的题目，最简单直接的方式是想办法增加数据量，如果是已经有几十万的双语语料，可以通过做伪数据的方式，如果更少，可以通过预训练，多语言等方式，如果极度稀缺，还有无监督的方式。描述中，中英应该不算选小语种，公开训练语料如WMT能有千万级别。至于中日，中韩训练语料没有详细调研过，如果语料实在太少，也可以通过枢轴语的方式，如训练中英，英日模型以达到中日的目的。英日在WMT也能有千万级别的平行语料。希望能帮到你。:)

**Comment by WIFIergege** [comment]
@xiaozhang521 方便加个微信吗？有些问题，还是想请教您一下，我的微信是：a15611851268，因为还有一些代码上的问题想请教您，不知道是否可以，我也是做这个相关的人，所以还是想请教像您这样的专业人士指点一下
