### ISSUE TITLE
”277页 3.神经元的输入...” 部分似乎有一点小错误

### ISSUE THREAD

**Issue by 20184365** [NiuTrans/MTBook#48]
> 于是你改变了三个输入的形式：
x1：10/距离（km） x2：150/票价（元）
x3：女朋友是否喜欢
在新修改的模型中，x0 和 x1 变成了连续变量，x2 仍然是离散变量，如图9.7所
示。

下标不一致

**Comment by mengxia-mx** [comment]
感谢您的反馈，我们马上修改 :) 笔芯
