### ISSUE TITLE
NMT inference阶段怎样用greedy search取得beam search的效果？

### ISSUE THREAD

**Issue by huchinlp** [NiuTrans/MTBook#5]
一般来说greedy search的翻译效果明显不如beam search，但后者实际运行的效率远低于前者，有没有工作探索过如何缩小两者在效果上的差距？如果可以做到这一点，那么inference的效率会提高不少。

**Comment by xiaotong** [comment]
实际上，我们最近也发现。经过一些手段，greedy search可以在NMT任务上取得很好的结果。单从BLEU上看，在有些任务（如WMT En-De）上gready search很逼近beam search。今年我们团队参加WNGT的比赛也对这方面做了尝试，后面也会分享。
