### ISSUE TITLE
编译过程第二个命令出现错误

### ISSUE THREAD

**Issue by Imsovegetable** [NiuTrans/MTBook#63]
![QQ图片20210514220127](https://user-images.githubusercontent.com/61308791/118281586-f715e700-b4ff-11eb-933b-afb572da92ed.png)

**Comment by Imsovegetable** [comment]
![QQ图片20210514221000](https://user-images.githubusercontent.com/61308791/118282707-2842e700-b501-11eb-9cde-213c5dc9a9f2.png)
执行第一个命令最后生成的pdf只有10页，不清楚是不是算成功了，内存已经扩充过了

**Comment by bigheadcrz** [comment]
![图片](https://user-images.githubusercontent.com/38352379/118287030-a73a1e80-b505-11eb-9575-5ab3603050d1.png)
从你的截图来看，你是不是用的命令行窗口编译的呢？我们通常是用Texworks打开tex文件，然后选择编译的指令进行编译，你可以试试这种方法看还有没有问题

**Comment by bigheadcrz** [comment]
![图片](https://user-images.githubusercontent.com/38352379/118287030-a73a1e80-b505-11eb-9575-5ab3603050d1.png)
从你的截图来看，你是不是用的命令行窗口编译的呢？我们通常是用Texworks打开tex文件，然后选择编译的指令进行编译，你可以试试这种方法看还有没有问题

**Comment by Imsovegetable** [comment]
> ![图片](https://user-images.githubusercontent.com/38352379/118287030-a73a1e80-b505-11eb-9575-5ab3603050d1.png)
> 从你的截图来看，你是不是用的命令行窗口编译的呢？我们通常是用Texworks打开tex文件，然后选择编译的指令进行编译，你可以试试这种方法看还有没有问题

您好，我用texworks编译的结果也是这样，在xelatex编译一遍后使用biber编译时，提示了类似的错误。
![1](https://user-images.githubusercontent.com/61308791/118289764-4233f800-b508-11eb-8bd3-80f3705b914e.png)
![2](https://user-images.githubusercontent.com/61308791/118289787-46601580-b508-11eb-9571-b4f357c4333d.png)

**Comment by bigheadcrz** [comment]
> 
> 
> > ![图片](https://user-images.githubusercontent.com/38352379/118287030-a73a1e80-b505-11eb-9575-5ab3603050d1.png)
> > 从你的截图来看，你是不是用的命令行窗口编译的呢？我们通常是用Texworks打开tex文件，然后选择编译的指令进行编译，你可以试试这种方法看还有没有问题
> 
> 您好，我用texworks编译的结果也是这样，在xelatex编译一遍后使用biber编译时，提示了类似的错误。
> ![1](https://user-images.githubusercontent.com/61308791/118289764-4233f800-b508-11eb-8bd3-80f3705b914e.png)
> ![2](https://user-images.githubusercontent.com/61308791/118289787-46601580-b508-11eb-9571-b4f357c4333d.png)

我之前没有遇到过类似的问题，不知道你有没有试过把MikTex以管理员身份安装到C盘，并且在MikTex Console里把宏包升级到最新版。如果还不能解决的话，你可以加我的QQ：854581319，我们再详细讨论一下这个问题

**Comment by Imsovegetable** [comment]
总结：错误是由windows中文用户名导致的，重新注册一个英文账号即可，感谢！
