### ISSUE TITLE
书中P294 疑问

### ISSUE THREAD

**Issue by 20184365** [NiuTrans/MTBook#66]
![屏幕截图 2021-06-16 195419](https://user-images.githubusercontent.com/43506763/122214461-b2a1b080-cedc-11eb-8083-38a50c605d48.png)

(C)应该是3阶张量，而且子张量维度应为 2x3 而不是3x2？

**Comment by xiaotong** [comment]
谢谢指出问题，这里确实是我们的笔误，会在后面的版本进行修正。
