### ISSUE TITLE
书本P347页内容勘误

### ISSUE THREAD

**Issue by 20184365** [NiuTrans/MTBook#67]
![image](https://user-images.githubusercontent.com/43506763/124339831-a52a3d00-dbe3-11eb-9dcb-8adb97241198.png)

这个图中的 x 处 不是点乘，是Hadamard product，在数学公式10.9中，一般的表示符号是空心小圆圈和带实心点的空心小圆圈。所以公式10.9和其上一段的“点乘”中文描述可能需要修改。

**Comment by isZengxin** [comment]
谢谢您的反馈，我们会尽快修改，再次感谢 :)
