### ISSUE TITLE
source code demo

### ISSUE THREAD

**Issue by baobaotql** [NiuTrans/MTBook#7]
如果增加一些source code demo就太好了

**Comment by bigheadcrz** [comment]
谢谢你的提议，我们之后会考虑增加demo的

**Comment by xiaotong** [comment]
> 如果增加一些source code demo就太好了

你好，谢谢对我们的关注。你希望的demo是什么样的，方便分享一下吗？

**Comment by baobaotql** [comment]
> 谢谢你的提议，我们之后会考虑增加demo的

好客气啊哈哈哈哈（手动滑稽）

**Comment by baobaotql** [comment]
> > 如果增加一些source code demo就太好了
> 
> 你好，谢谢对我们的关注。你希望的demo是什么样的，方便分享一下吗？

老师您好，可能我也没有全看完，但是看前面一些章节的话，像比较简单的n-gram、分词或者句法分析，在章节后可以增加一些demo，像是大家看的比较多的Python自然语言处理(书)或者吴恩达开源教程(书)在github上除了教程分享也有source code demo的；然后后面我看了比较感兴趣的attention、seq2seq、transfromer，这个在github上像比较火的nlp-tutorial，也是会有教程、论文及附上demo，大家看完教程然后趁热写demo蛮好；如果能结合小牛api教程其实也蛮不错    
最后祝小牛越来越好  NEU_CSEer

**Comment by xiaotong** [comment]
谢谢意见，我们会逐步把slides和代码开放出来。而且最近很多人给我们提了很多意见，我们也在计划重构整个教程，相信会越来越好！
