### ISSUE TITLE
勘误 章节 8.2.1 p224 

### ISSUE THREAD

**Issue by smartmark-pro** [NiuTrans/MTBook#77]
"这项工作也获得了自然语言处理领域顶级会议 ACL2015 的最佳论文奖"
看了下索引88的文献, 它是2005年的最佳论文奖. https://aclanthology.org/P05-1033/

另外想说下一个小细节, 参考文献, index 之类的能不能放到左侧pdf目录中

**Comment by bigheadcrz** [comment]
谢谢，这块儿的确是我们写错了，之后我们会更新纠正这个错误。你的建议我们也会参考的
