### ISSUE TITLE
年代错误

### ISSUE THREAD

**Issue by Shuai-GAO** [NiuTrans/MTBook#78]
文中1.2.2 机器翻译的萌芽部分：

"早在17 世纪，如Descartes、Leibniz、Cave Beck、Athanasius Kircher 和Johann Joachim Becher 等很多学者就提出采用机器词典（电子词典）来克服语言障碍的想法[4]，这种想法在当时是很超前的。随着语言学、计算机科学等学科的发展，在19 世纪30 年代使用计算模型进行自动翻译的思想开始萌芽，如当时法国科学家Georges Artsrouni 就提出用机器来进行翻译的想法。只是那时依然没有合适的实现手段，所以这种想法的合理性无法被证实。"

应将“19世纪30年代”改为“20世纪30年代”。

**Comment by shanweiqiao** [comment]
> 文中1.2.2 机器翻译的萌芽部分：
> 
> "早在17 世纪，如Descartes、Leibniz、Cave Beck、Athanasius Kircher 和Johann Joachim Becher 等很多学者就提出采用机器词典（电子词典）来克服语言障碍的想法[4]，这种想法在当时是很超前的。随着语言学、计算机科学等学科的发展，在19 世纪30 年代使用计算模型进行自动翻译的思想开始萌芽，如当时法国科学家Georges Artsrouni 就提出用机器来进行翻译的想法。只是那时依然没有合适的实现手段，所以这种想法的合理性无法被证实。"
> 
> 应将“19世纪30年代”改为“20世纪30年代”。
收到，感谢指出错误，已更正
