### ISSUE TITLE
勘误：11.14 图片与标注不符

### ISSUE THREAD

**Issue by borgwang** [NiuTrans/MTBook#80]
第 11 章图 11.14 中，图示左边的绿框表示 A 作为门控参数，右边 B 表示提取的特征，输出 y 的表达式应该是 $y=\sigma(A) \otimes B$，书中为 $y=A \otimes \sigma(B)$。

后文中以 $y=A \otimes \sigma(B)$ 为准描述，应该修改图示为右边的绿框连接 sigmoid 运算。

![image](https://user-images.githubusercontent.com/20679515/140668719-911b5298-195c-413a-bd92-08c9f7001f65.png)

**Comment by shanweiqiao** [comment]
> 第 11 章图 11.14 中，图示左边的绿框表示 A 作为门控参数，右边 B 表示提取的特征，输出 y 的表达式应该是 $y=\sigma(A) \otimes B$，书中为 $y=A \otimes \sigma(B)$。
> 
> 后文中以 $y=A \otimes \sigma(B)$ 为准描述，应该修改图示为右边的绿框连接 sigmoid 运算。
> 
> ![image](https://user-images.githubusercontent.com/20679515/140668719-911b5298-195c-413a-bd92-08c9f7001f65.png)

收到，已勘误，感谢指正
