### ISSUE TITLE
能否提供一个读者交流群

### ISSUE THREAD

**Issue by jothan706** [NiuTrans/MTBook#81]
你好，很感谢你们为机器翻译领域带来一本这么优秀的书籍，读下来获益良多，我也在你们的实体书出版后买了一本，不知道有没有可能建一个微信群聊，方便读者和NiuTrans以及机器翻译领域的各位大牛进行持续的技术交流呢？

**Comment by shanweiqiao** [comment]
您好，非常感谢您的建议，我们也非常希望和更多的人一起沟通并相互学习。但是出于一些管理上的考虑，短期内不方便组建微信群聊，十分抱歉。如果您对我们的研究工作十分感兴趣，希望您通过浏览我们实验室的[主页](https://www.nlplab.com/)，寻找您感兴趣的方向，并通过邮件与[我们](https://www.nlplab.com/team)交流
