### ISSUE TITLE
捉个typo

### ISSUE THREAD

**Issue by Yaoming95** [NiuTrans/MTBook#87]
《机器翻译》的作者们与编辑们，您们好。阅读您们的著作受益匪浅，这里捉一个小typo。
 17.2.2节 “其中的部分概念在后续介绍的端到端语言翻译中也会有所涉及”。 结合下文，语言翻译 应为 语音翻译。

**Comment by xiaotong** [comment]
非常感谢你的修改建议。我们已经在源码中将问题修正，后续会更新到网页上。
